### ISSUE TITLE
doc/readthedocs bug

### ISSUE THREAD

**Issue by hwine** [Zsailer/sphinx-pydantic#1]
Just heard about this project - it looks awesome!

It happened to catch my eye that the docs are not rendering correctly on https://sphinx-pydantic.readthedocs.io/. The details of the ``pip`` command are not shown.

On GitHub:
![image](https://user-images.githubusercontent.com/132412/69502838-8375b980-0ec8-11ea-9b73-8ff715b0be51.png)

On readthedocs:
![image](https://user-images.githubusercontent.com/132412/69502864-bc159300-0ec8-11ea-80ee-b63cb4da05d0.png)

**Comment by Zsailer** [comment]
Fixed! Thanks, @hwine.
